CREATE DATABASE EduHub;
USE EduHub;
CREATE TABLE COURSES(
CourseID VARCHAR(100),
CourseDesc VARCHAR(300)
);
CREATE TABLE STUDENTS(
StudentID INT(6),
FName VARCHAR(10),
LName VARCHAR(10),
Email VARCHAR(50)
);
CREATE TABLE UNIVERSITY(
CollegeName VARCHAR(100)
);
CREATE TABLE REVIEW(
Review VARCHAR(300),
Professor VARCHAR(30),
Grade VARCHAR(2)
);
